CallCentre/Controllers/CallLogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CallCentre.Models;

namespace CallCentre.Controllers
{
    public class CallLogController : Controller
    {
        private CallCentreContext db = new CallCentreContext();

        // GET: /CallLog/
        public ActionResult Index()
        {
            var calllogs = db.CallLogs.Include(c => c.Contact);
            return View(calllogs.ToList());
        }

        // GET: /CallLog/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CallLog calllog = db.CallLogs.Find(id);
            if (calllog == null)
            {
                return HttpNotFound();
            }
            return View(calllog);
        }

        // GET: /CallLog/Create
        public ActionResult Create()
        {
            ViewBag.ContactId = new SelectList(db.Contacts, "Id", "Name");

            CallLog callLog = new CallLog();
            callLog.CallDate = DateTime.Now;

            return View(callLog);
        }

        // POST: /CallLog/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,ContactId,Message,CallDate")] CallLog calllog)
        {
            if (ModelState.IsValid)
            {
                db.CallLogs.Add(calllog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ContactId = new SelectList(db.Contacts, "Id", "Name", calllog.ContactId);
            return View(calllog);
        }

        // GET: /CallLog/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CallLog calllog = db.CallLogs.Find(id);
            if (calllog == null)
            {
                return HttpNotFound();
            }
            ViewBag.ContactId = new SelectList(db.Contacts, "Id", "Name", calllog.ContactId);
            return View(calllog);
        }

        // POST: /CallLog/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,ContactId,Message,CallDate")] CallLog calllog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(calllog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ContactId = new SelectList(db.Contacts, "Id", "Name", calllog.ContactId);
            return View(calllog);
        }

        // GET: /CallLog/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CallLog calllog = db.CallLogs.Find(id);
            if (calllog == null)
            {
                return HttpNotFound();
            }
            return View(calllog);
        }

        // POST: /CallLog/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CallLog calllog = db.CallLogs.Find(id);
            db.CallLogs.Remove(calllog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CallCentre/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Call Centre</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Call Centre", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Contact", "Index", "Contact")</li>
                    <li>@Html.ActionLink("Call Log", "Index", "CallLog")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Nelson Chan</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>